name: Deploy to AKS
description: deploys application
inputs:
  environment:
    description: Environment to deploy to
    required: true
  sha:
    description: Commit sha to be deployed
    required: true
  azure-credentials:
    description: Credentials for azure
    required: true
  pr:
    description: Pull Request Reference
    required: false

outputs:
  deploy-url:
    value: ${{ steps.set_env_var.outputs.deploy_url }}
runs:
  using: composite
  steps:
    - name: Set Environment variables
      id: set_env_var
      shell: bash
      run: |
        tf_vars_file=terraform/aks/config/${{ inputs.environment }}.tfvars.json
        echo " tf_vars_file is $tf_vars_file"
        terraform_version=$(awk '/{/{f=/^terraform/;next}f' terraform/aks/terraform.tf | grep -o [0-9\.]*)
        echo "cluster=$(jq -r '.cluster' ${tf_vars_file})" >> $GITHUB_ENV
        echo "aks_app_environment=$(jq -r '.environment' ${tf_vars_file})" >> $GITHUB_ENV
        echo "TERRAFORM_VERSION=$terraform_version" >> $GITHUB_ENV
        echo "namespace=$(jq -r '.namespace' ${tf_vars_file})" >> $GITHUB_ENV
        if [[ $cluster == 'production' ]]; then
              echo "deploy_url=https://get-school-experience-${{ env.aks_app_environment }}.teacherservices.cloud" >> $GITHUB_OUTPUT
            else
              echo "deploy_url=https://get-school-experience-${{ env.aks_app_environment }}.${cluster}.teacherservices.cloud" >> $GITHUB_OUTPUT
        fi

    - name: Use Terraform ${{ env.TERRAFORM_VERSION }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - uses: DFE-Digital/github-actions/set-arm-environment-variables@master
      with:
        azure-credentials: ${{ inputs.azure-credentials }}

    - name: Get Short SHA
      id: sha
      shell: bash
      run: echo "short=$(echo "${{ inputs.sha }}" | cut -c -7)" >> $GITHUB_OUTPUT

    - name: Print Sha
      id: print-sha-environment
      shell: bash
      run: |
        echo "${{ inputs.sha }}"
        echo "the passed in environment is ${{ inputs.environment  }}"
        echo terraform version

    - name: Terraform init, plan & apply
      shell: bash
      run: |
        envval="${{ inputs.environment }}_aks"
        echo "envval is ${envval}"
        make ci ${envval} terraform-apply-aks PR_NUMBER=${{ inputs.pr }}
      env:
        IMAGE_TAG: ${{ steps.sha.outputs.short }}
