  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          School Experience 
  DOCKER_REPOSITORY:     ghcr.io/dfe-digital/schools-experience
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           School Experience
  REVIEW_APPLICATION:    review-school-experience
  PAAS_APPLICATION_NAME: school-experience
