  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          School Experience
  DOCKER_REPOSITORY:     ghcr.io/dfe-digital/schools-experience
  DOMAIN:                london.cloudapps.digital
  REVIEW_AKS_DOMAIN:     test.teacherservices.cloud
  APPLICATION:           School Experience
  REVIEW_APPLICATION:    review-school-experience
  AKS_REVIEW_APPLICATION: get-school-experience-review-pr
  PAAS_APPLICATION_NAME: school-experience-app
