version: 2
updates:

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    ignore:
          # TODO: Remove this ignore config once moved to a Redis v6.2+ instance in AKS.
          # The version is currently pinned to <7. We're unable to upgrade sidekiq as it requires out Redis service
          # instance to be 6.2+ https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md#version-support.
          # Our current Redis service instance is 5.0.6. This will be upgraded when we migrate to AKS.
          - dependency-name: "sidekiq"
            update-types: ["version-update:semver-major"]

          # TODO: Remove this ignore config once moved to a Redis v6.2+ instance in AKS.
          # The version is currently pinned to <5 by sidekiq (version 6.5.8).
          # It seems this pin is removed by later sidekiq versions, but we're unable to upgrade sidekiq as it requires out
          # Redis service instance to be 6.2+ https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md#version-support.
          # Our current Redis service instance is 5.0.6.
          - dependency-name: "redis"
            update-types: ["version-update:semver-major"]


  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: /terraform/aks/
    schedule:
      interval: daily
