inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Gemspec/RequiredRubyVersion:
  Exclude:
    - node_modules/dfe-autocomplete/dfe-autocomplete.gemspec

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Layout/ArgumentAlignment:
  Enabled: false

# We have specific keywords we need to receive but not use in the error handler
# for Redis connections
Lint/UnusedBlockArgument:
  Exclude:
    - config/environments/*

Lint/MissingSuper:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/StringConcatenation:
  Enabled: false

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# Brakeman (which relies on ruby-parser) does not yet support this syntax
# See https://github.com/seattlerb/ruby_parser/issues/326
Style/HashSyntax:
  EnforcedShorthandSyntax: never

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/HttpPositionalArguments:
  Exclude:
    - spec/controllers/candidates/dashboard_base_controller_spec.rb

# Excluded for cancellation because we use the same model for both school
# and candidate cancellations
Rails/InverseOf:
  Exclude:
    - app/models/bookings/placement_request/cancellation.rb

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/dev_ssl_generator.rake
    - lib/tasks/cucumber.rake

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - servertest
    - staging
    - production

# These are considered safe to autofix but are not actually redundant
Rails/RedundantForeignKey:
  Exclude:
    - app/models/bookings/placement_date.rb
    - app/models/bookings/placement_request.rb
    - app/models/bookings/school.rb
    - app/models/event.rb
    - app/models/schools/school_profile.rb

# These break the build right now so we want to work thorugh them slowly
Rails/SaveBang:
  Enabled: false

Style/DateTime:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false
