inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - spec_external/**/*

Layout/ArgumentAlignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/dev_ssl_generator.rake
    - lib/tasks/cucumber.rake
