inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - spec_external/**/*

Layout/ArgumentAlignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

# Excluded for cancellation because we use the same model for both school
# and candidate cancellations
Rails/InverseOf:
  Exclude:
    - app/models/bookings/placement_request/cancellation.rb

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/dev_ssl_generator.rake
    - lib/tasks/cucumber.rake

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - servertest
    - production
