variables:
  imageTag: v$(Build.BuildId)
  POSTGRES_IMAGE: mdillon/postgis:11-alpine
  # define four more variables imageName, DOCKER_HUB_REPO in the build pipeline in UI
  POSTGRESS_PASSWORD: secret
  DATABASE_URL: postgis://postgres:secret@postgres/school_experience_test
  WEB_URL: postgis://postgres:secret@postgres/school_experience
  SECRET_KEY_BASE: stubbed
  REDIS_IMAGE: redis:5-alpine
  REDIS_URL: redis://redis:6379/1
  CUCUMBER_PROFILE: continuous_integration
  APP_URL: http://school-experience:3000

jobs:
- job: BuildAndNonBrowserTesting
  pool:
    vmImage: 'ubuntu-16.04'

  steps:

  - script: echo $(Build.Reason)
    displayName: Build trigger

  - script: docker run --name=postgres -e POSTGRES_PASSWORD -d $(POSTGRES_IMAGE)
    displayName: Launch Postgres # done early to give it time to boot

  - script: docker run --name=redis -d $(REDIS_IMAGE)
    displayName: Launch Redis # done early to give it time to boot

  - script: |
      DEPENDENCY_TAG=`cat Dockerfile .dockerignore Gemfile Gemfile.lock package.json yarn.lock | shasum | cut -d ' ' -f 1`
      echo "##vso[task.setvariable variable=buildCacheTag]${DEPENDENCY_TAG}"
    displayName: Calculate build cache tag

  - script: echo "dependencies tag is $(buildCacheTag)"
    displayName: Show build cache tag

  - script: |
      docker pull $(DOCKER_HUB_REPO):$(buildCacheTag) || true
      docker build -f Dockerfile --cache-from=$(DOCKER_HUB_REPO):$(buildCacheTag) -t $(DOCKER_HUB_REPO):$(imageTag) .
    displayName: Build Docker Image using Cache
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: docker build -f Dockerfile -t $(DOCKER_HUB_REPO):$(imageTag) .
    displayName: Build Docker Image without Cache
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: docker tag $(DOCKER_HUB_REPO):$(imageTag) $(DOCKER_HUB_REPO):$(buildCacheTag)
    displayName: Tag build cache image
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: Docker@2
    displayName: 'Upload build cache image to DockerHub'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      containerRegistry: $(DOCKER_HUB_CONNECTION_NAME)
      repository: $(DOCKER_HUB_REPO)
      command: push
      tags: $(buildCacheTag)

  - script: docker run --rm --link postgres:postgres -e DATABASE_URL --link redis:redis -e REDIS_URL -e RAILS_ENV=test $(DOCKER_HUB_REPO):$(imageTag) rake db:create db:test:prepare
    displayName: Create Testing databases, import schema and fixtures
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL --link redis:redis -e REDIS_URL -e RAILS_ENV=test $(DOCKER_HUB_REPO):$(imageTag) rspec
    displayName: Run the Specs
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL --link redis:redis -e REDIS_URL -e RAILS_ENV=test -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true -e CUC_PAGE_DELAY=0 $(DOCKER_HUB_REPO):$(imageTag) cucumber --profile=$(CUCUMBER_PROFILE)
    displayName: Run the Cucumber features
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL --link redis:redis -e REDIS_URL -e RAILS_ENV=test $(DOCKER_HUB_REPO):$(imageTag) brakeman --no-pager
    displayName: Run the Brakeman security scan
  - script: docker run --rm --link postgres:postgres --link redis:redis -e DATABASE_URL="$WEB_URL" -e REDIS_URL -e SECRET_KEY_BASE=stubbed $(DOCKER_HUB_REPO):$(imageTag) rake db:create db:schema:load
    displayName: Create Smoketest database and import schema
  - script: docker run -d --name=smoketest --health-interval=4s --link postgres:postgres --link redis:redis -e RAILS_ENV=servertest -e DATABASE_URL="$WEB_URL" -e REDIS_URL -e SECRET_KEY_BASE=stubbed -e SKIP_FORCE_SSL=true $(DOCKER_HUB_REPO):$(imageTag)
    displayName: Spin up app
  - script: sleep 15 # ugly but gives the web app time to boot
    displayName: Pause to allow app to boot
  - script: docker ps | grep smoketest | grep '(healthy)' || false
    displayName: Check app reports as Healthy
  - script: docker run --rm --link postgres:postgres --link redis:redis -e DATABASE_URL -e REDIS_URL -e RAILS_ENV=test $(DOCKER_HUB_REPO):$(imageTag) govuk-lint-ruby app lib spec
    displayName: Run the GovUK Lint check

  - script: |
      docker tag $(DOCKER_HUB_REPO):$(imageTag) $(DOCKER_HUB_REPO):latest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Push Docker image (built from master)'

  - task: Docker@2
    displayName: 'push to docker hub'
    inputs:
      containerRegistry: $(DOCKER_HUB_CONNECTION_NAME)
      repository: $(DOCKER_HUB_REPO)
      command: push
      tags: $(imageTag)

  - task: Docker@2
    displayName: 'push to docker hub'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      containerRegistry: $(DOCKER_HUB_CONNECTION_NAME)
      repository: $(DOCKER_HUB_REPO)
      command: push
      tags: latest

  - task: Bash@3
    name: mtrx
    displayName: 'set up functional test matrix variable'
    inputs:
      targetType: filePath
      filePath: ./script/generate_matrix.sh

- job: FunctionalTesting
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn: BuildAndNonBrowserTesting
  strategy:
    maxParallel: 5
    matrix: $[ dependencies.BuildAndNonBrowserTesting.outputs['mtrx.legs'] ]

  steps:

  - script: |
      docker pull $(DOCKER_HUB_REPO):$(imageTag)
      docker tag $(DOCKER_HUB_REPO):$(imageTag) school-experience:latest
      docker-compose -f docker-compose.yml -f docker-compose-$(browser).yml up -d
      WAIT_COUNT=0
      until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ $WAIT_COUNT -eq 12 ]; do echo "WAIT COUNT $(( WAIT_COUNT++ ))" && sleep 5 ; done
      echo SELENIUM_HUB_HOSTNAME=selenium-$(browser) CUC_DRIVER=$(browser) with features... $(features)
      docker-compose -f docker-compose.yml -f docker-compose-$(browser).yml run --rm -e RAILS_ENV=test -e SELENIUM_HUB_HOSTNAME=selenium-$(browser) -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true -e APP_URL -e CUC_DRIVER=$(browser) school-experience cucumber $(features)
    displayName: Run Cucumber Tests

- job: PublishArtifacts
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn:
  - FunctionalTesting

  steps:

  - task: CopyFiles@2
    inputs:
      contents: 'script/compose-school-experience.sh'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy Docker Compose file to staging area'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/script/compose-school-experience.sh
      artifactName: 'compose-file'
    displayName: 'Publish the Docker Compose file'
