pool:
  vmImage: 'ubuntu-16.04'

variables:
  imageName: school-experience
  imageTag: $(Build.BuildId)
  POSTGRES_IMAGE: mdillon/postgis:11-alpine
  # define three more variables dockerId, dockerPassword and dockerRegistry in the build pipeline in UI
  POSTGRESS_PASSWORD: secret
  DATABASE_URL: postgis://postgres:secret@postgres/school_experience_test
  WEB_URL: postgis://postgres:secret@postgres/school_experience
  SECRET_KEY_BASE: stubbed

steps:
  - script: docker login $(dockerRegistry) -u $(dockerId) -p $pswd
    env:
      pswd: $(dockerPassword)
    displayName: 'Docker login'
  - script: docker run --name=postgres -e POSTGRES_PASSWORD -d $(POSTGRES_IMAGE)
    displayName: Launch Postgres # done early to give it time to boot
  - script: docker build -f Dockerfile -t $(dockerRegistry)/$(imageName):$(imageTag) .
    displayName: Build Docker Image $(imageName):$(imageTag)
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL -e RAILS_ENV=test $(dockerRegistry)/$(imageName):$(imageTag) rake db:create db:test:prepare
    displayName: Create Testing databases, import schema and fixtures
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL -e RAILS_ENV=test $(dockerRegistry)/$(imageName):$(imageTag) rspec
    displayName: Run the Specs
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL -e RAILS_ENV=test -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true $(dockerRegistry)/$(imageName):$(imageTag) cucumber
    displayName: Run the Cucumber features
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL -e RAILS_ENV=test $(dockerRegistry)/$(imageName):$(imageTag) brakeman --no-pager
    displayName: Run the Brakeman security scan
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL="$(WEB_URL)" -e SECRET_KEY_BASE=stubbed $(dockerRegistry)/$(imageName):$(imageTag) rake db:create db:schema:load
    displayName: Create Smoketest database and import schema
  - script: docker run -d --name=smoketest --health-interval=4s --link postgres:postgres -e DATABASE_URL="$(WEB_URL)" -e SECRET_KEY_BASE=stubbed $(dockerRegistry)/$(imageName):$(imageTag)
    displayName: Spin up app
  - script: sleep 15 # ugly but gives the web app time to boot
    displayName: Pause to allow app to boot
  - script: docker ps | grep smoketest | grep '(healthy)' || false
    displayName: Check app reports as Healthy
  - script: docker run --rm --link postgres:postgres -e DATABASE_URL -e RAILS_ENV=test $(dockerRegistry)/$(imageName):$(imageTag) govuk-lint-ruby app lib spec
    displayName: Run the GovUK Lint check
  - script: docker push $(dockerRegistry)/$(imageName):$(imageTag)
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    displayName: 'Push Docker image'