version: '3.3'

services:

   selenium-chrome:
     image: selenium/standalone-chrome
     volumes:
       - /dev/shm:/dev/shm

   selenium-firefox:
     image: selenium/standalone-firefox
     volumes:
       - /dev/shm:/dev/shm

