---
:shared:
  :users_roles:
  - user_id
  :users:
  - id
  - sub
  :bookings_school_searches:
  - query
  - location
  - coordinates
  :bookings_candidates:
  - id
  :bookings_profiles:
  - admin_contact_email
  - admin_contact_email_secondary
  - admin_contact_phone
  :bookings_placement_requests:
  - candidate_id
  :events:
  - bookings_candidate_id
