---
:shared:
  :bookings_placement_request_cancellations:
  - reason
  - extra_details
  :schools_school_profiles:
  - candidate_requirement_requirements_details
  - administration_fee_description
  - dbs_fee_description
  - other_fee_description
  - description_details
  - candidate_dress_code_other_dress_requirements_detail
  - candidate_parking_information_parking_details
  - candidate_parking_information_nearby_parking_details
  - candidate_experience_detail_disabled_facilities_details
  - experience_outline_candidate_experience
  - teacher_training_teacher_training_details
  - teacher_training_teacher_training_url
  - admin_contact_full_name
  - admin_contact_email
  - admin_contact_phone
  - candidate_experience_schedule_times_flexible_details
  - admin_contact_email_secondary
  - dbs_requirement_dbs_policy_details
  - dbs_requirement_no_dbs_policy_details
  - candidate_requirements_selection_other_details
  - access_needs_detail_description
  - access_needs_policy_url
  - candidate_requirements_selection_photo_identification_details
  - dbs_requirement_dbs_policy_details_inschool
  :candidates_session_tokens:
  - id
  - token
  - candidate_id
  - expired_at
  - created_at
  - updated_at
  - confirmed_at
  :bookings_candidates:
  - gitis_uuid
  :bookings_bookings:
  - placement_details
  - contact_name
  - contact_number
  - contact_email
  - candidate_instructions
  :bookings_profiles:
  - description_details
  - dress_code_other_details
  - parking_details
  - experience_details
  - teacher_training_info
  - teacher_training_url
  - admin_contact_full_name
  - admin_contact_email
  - admin_contact_phone
  - administration_fee_description
  - dbs_fee_description
  - other_fee_description
  - flexible_on_times_details
  - admin_contact_email_secondary
  - dbs_policy_details
  - access_needs_description
  - access_needs_policy_url
  - dbs_policy_conditions
  :feedbacks:
  - reason_for_using_service_explanation
  - unsuccessful_visit_explanation
  :bookings_schools:
  - contact_email
  - placement_info
  - teacher_training_info
  - primary_key_stage_info
  - availability_info
  :bookings_placement_requests:
  - degree_stage_explaination
  - token
