---
:shared:
  :users:
  - id
  - sub
  - created_at
  - updated_at
  :schools_on_boarding_profile_subjects:
  - id
  - schools_school_profile_id
  - bookings_subject_id
  - created_at
  - updated_at
  :bookings_placement_request_cancellations:
  - id
  - bookings_placement_request_id
  - created_at
  - updated_at
  - cancelled_by
  - sent_at
  - viewed_at
  - rejection_category
  - fully_booked
  - accepted_on_ttc
  - date_not_available
  - no_relevant_degree
  - no_phase_availability
  - candidate_not_local
  - duplicate
  - info_not_provided
  - cancelation_requested
  - wrong_choice_secondary
  - wrong_choice_primary
  - other
  :schools_school_profiles:
  - id
  - created_at
  - updated_at
  - candidate_requirement_dbs_requirement
  - candidate_requirement_dbs_policy
  - candidate_requirement_requirements
  - fees_administration_fees
  - fees_dbs_fees
  - fees_other_fees
  - administration_fee_amount_pounds
  - administration_fee_interval
  - administration_fee_payment_method
  - dbs_fee_amount_pounds
  - dbs_fee_interval
  - dbs_fee_payment_method
  - other_fee_amount_pounds
  - other_fee_interval
  - other_fee_payment_method
  - phases_list_primary
  - phases_list_secondary
  - phases_list_college
  - key_stage_list_early_years
  - key_stage_list_key_stage_1
  - key_stage_list_key_stage_2
  - candidate_dress_code_business_dress
  - candidate_dress_code_cover_up_tattoos
  - candidate_dress_code_remove_piercings
  - candidate_dress_code_smart_casual
  - candidate_dress_code_other_dress_requirements
  - candidate_parking_information_parking_provided
  - candidate_experience_detail_disabled_facilities
  - candidate_experience_schedule_start_time
  - candidate_experience_schedule_end_time
  - candidate_experience_schedule_times_flexible
  - teacher_training_provides_teacher_training
  - bookings_school_id
  - phases_list_secondary_and_college
  - confirmation_acceptance
  - administration_fee_step_completed
  - dbs_fee_step_completed
  - other_fee_step_completed
  - dbs_requirement_requires_check
  - candidate_requirements_selection_on_teacher_training_course
  - candidate_requirements_selection_live_locally
  - candidate_requirements_selection_maximum_distance_from_school
  - candidate_requirements_selection_other
  - access_needs_support_supports_access_needs
  - candidate_requirements_selection_step_completed
  - candidate_requirements_selection_not_on_another_training_course
  - candidate_requirements_selection_has_or_working_towards_degree
  - disability_confident_is_disability_confident
  - access_needs_policy_has_access_needs_policy
  - candidate_requirements_selection_provide_photo_identification
  - dbs_requirement_dbs_policy_conditions
  - candidate_dress_code_step_completed
  :candidates_booking_feedbacks:
  - id
  - bookings_booking_id
  - gave_realistic_impression
  - covered_subject_of_interest
  - influenced_decision
  - intends_to_apply
  - effect_on_decision
  - created_at
  - updated_at
  :bookings_subjects:
  - id
  - name
  - created_at
  - updated_at
  - hidden
  - secondary_subject
  :bookings_schools_subjects:
  - id
  - bookings_school_id
  - bookings_subject_id
  - created_at
  - updated_at
  :bookings_schools_phases:
  - id
  - bookings_school_id
  - bookings_phase_id
  - created_at
  - updated_at
  :bookings_school_types:
  - id
  - name
  - edubase_id
  - created_at
  - updated_at
  :bookings_school_searches:
  - id
  - query
  - location
  - radius
  - subjects
  - phases
  - max_fee
  - page
  - number_of_results
  - coordinates
  - created_at
  - updated_at
  - analytics_tracking_uuid
  - dbs_policies
  - disability_confident
  - parking
  :bookings_schools:
  - id
  - name
  - coordinates
  - created_at
  - updated_at
  - fee
  - urn
  - website
  - address_1
  - address_2
  - address_3
  - town
  - county
  - postcode
  - bookings_school_type_id
  - teacher_training_provider
  - teacher_training_website
  - enabled
  - availability_preference_fixed
  - views
  - experience_type
  :bookings_profiles:
  - id
  - school_id
  - dbs_required
  - dbs_policy
  - individual_requirements
  - primary_phase
  - secondary_phase
  - college_phase
  - key_stage_early_years
  - key_stage_1
  - key_stage_2
  - dress_code_business
  - dress_code_cover_tattoos
  - dress_code_remove_piercings
  - dress_code_smart_casual
  - parking_provided
  - disabled_facilities
  - start_time
  - end_time
  - flexible_on_times
  - administration_fee_amount_pounds
  - administration_fee_interval
  - administration_fee_payment_method
  - dbs_fee_amount_pounds
  - dbs_fee_interval
  - dbs_fee_payment_method
  - other_fee_amount_pounds
  - other_fee_interval
  - other_fee_payment_method
  - created_at
  - updated_at
  - dbs_requires_check
  - supports_access_needs
  - disability_confident
  - has_access_needs_policy
  - admin_contact_email
  - admin_contact_email_secondary
  - admin_contact_phone
  :bookings_placement_date_subjects:
  - id
  - bookings_placement_date_id
  - bookings_subject_id
  - created_at
  - updated_at
  :bookings_placement_dates:
  - id
  - date
  - created_at
  - updated_at
  - duration
  - active
  - bookings_school_id
  - max_bookings_count
  - published_at
  - subject_specific
  - supports_subjects
  - virtual
  - end_availability_offset
  - start_availability_offset
  - recurring
  - publishable
  :bookings_phases:
  - id
  - name
  - created_at
  - updated_at
  - position
  - edubase_id
  - supports_subjects
  :bookings_candidates:
  - gitis_uuid
  - id
  - created_at
  - updated_at
  - confirmed_at
  - created_in_gitis
  :bookings_placement_requests:
  - id
  - objectives
  - urn
  - degree_stage
  - degree_subject
  - teaching_stage
  - subject_first_choice
  - subject_second_choice
  - has_dbs_check
  - created_at
  - updated_at
  - availability
  - bookings_placement_date_id
  - bookings_school_id
  - analytics_tracking_uuid
  - viewed_at
  - candidate_id
  - bookings_subject_id
  - under_consideration_at
  - experience_type
  :bookings_bookings:
  - id
  - date
  - bookings_subject_id
  - bookings_placement_request_id
  - bookings_school_id
  - created_at
  - updated_at
  - location
  - duration
  - accepted_at
  - attended
  - experience_type
  :feedbacks:
  - id
  - type
  - reason_for_using_service
  - rating
  - improvements
  - created_at
  - updated_at
  - urn
  - successful_visit
  - referrer
  :events:
  - id
  - bookings_school_id
  - event_type
  - recordable_id
  - recordable_type
  - created_at
  - updated_at
  - bookings_candidate_id
  :users_roles:
  - user_id
  - role_id
  - created_at
  - updated_at
  :roles:
  - id
  - name
  - resource_type
  - resource_id
  - created_at
  - updated_at
