version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
