name: Build and Deploy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ feature/11223344-next-mapping ]

permissions:
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write

jobs:

  deployments_aks:
    name: Deployments aks
    environment:
       name: development_aks
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Environment variables

        shell: bash
        run: |
          make review_test get-cluster-credentials CONFIRM_TEST=yes
          kubectl get svc  -n git-development
          echo "kubequery=$(kubectl get ing -o=custom-columns=NAME:.metadata.name,SVCs:..service.name -n git-development)" >> $GITHUB_ENV
          echo "result ${{ env.kubequery }}"
