name: Build and Deploy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ feature/11223344-next-mapping ]

permissions:
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write

jobs:

  deployments_aks:
    name: Deployments aks
    environment:
       name: development_aks
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Environment variables

        shell: bash
        run: |
          make review_test get-cluster-credentials CONFIRM_TEST=yes
          NAMESPACE="default"

          # Prefix to search for
          PREFIX="get-school-experience-review-pr"

          # Query ingresses and filter by prefix
          INGS=$(kubectl get ing -n ${NAMESPACE} -o json | \
            jq -r '.items[] | select(.metadata.name | startswith("'${PREFIX}'"))')

          echo "Ingress Name - Service"
          for ing in ${INGS}; do

            # Get name
            NAME=$(echo ${ing} | jq -r '.metadata.name')

            # Get service name
            SVC=$(echo ${ing} | jq -r '.spec.rules[0].http.paths[0].backend.service.name')

            # Print output
            echo "${NAME} - ${SVC}"

          done
