name: Pull Requests
on:
  repository_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  DOCKERHUB_REPOSITORY: dfedigital/school-experience
  CONTAINER: school-experience
  CUCUMBER_PROFILE: continuous_integration

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.4

    steps:
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/checkout@v2

      - name: Get Short SHA
        id: sha
        run: echo ::set-output name=short::$(git rev-parse --short $GITHUB_SHA)

      - name: Set DOCKER_IMAGE environment variable
        run: echo ::set-env name=DOCKER_IMAGE::${{ env.DOCKERHUB_REPOSITORY }}:sha-${{ steps.sha.outputs.short }}

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
             dockerfile: "Dockerfile"

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.6'

      - name: Install Bundler
        run: |-
          gem install bundler --version=2.1.4

      - name: Bundle install
        run: |
          bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
          bundle config set without development
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Brakeman security scan
        run: |-
          bundle exec \
            brakeman --no-pager

      - name: Run GovUK Lint check
        run: |-
          bundle exec \
            rubocop app config lib features spec spec_external --format clang

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v1

      - name: Add ouput folders
        run: mkdir ${PWD}/out && mkdir ${PWD}/out/specs && mkdir ${PWD}/out/coverage && mkdir ${PWD}/out/features

      - name: Build Docker Compose container
        run: |-
          docker-compose -f docker-compose-local.yml build

      - name: Create Docker Compose stack
        run: |-
          docker-compose -f docker-compose-local.yml up -d
          WAIT_COUNT=0
          until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ $WAIT_COUNT -eq 12 ] ; do echo "WAIT COUNT $(( WAIT_COUNT++ ))" && sleep 5 ; done

      - name: Run Specs
        run: |-
          docker-compose -f docker-compose-local.yml run --rm -v ${PWD}/out/specs:/app/out -v ${PWD}/out/coverage:/app/coverage db-tasks \
            rspec --format documentation --format RspecSonarqubeFormatter --out /app/out/test-report.xml

      - name: Upload Spec Results
        uses: actions/upload-artifact@v2
        with:
          name: Spec_Results
          path: ${PWD}/out/specs/*

      - name: Fixup report file paths
        run: sudo sed -i "s?\"/app/?\"${PWD}/?" ${PWD}/out/coverage/.resultset.json

      - name: Upload Code Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: Code_Coverage
          path: ${PWD}/out/coverage/*

      - name: Run Cucumber features
        run: |-
          docker-compose -f docker-compose-local.yml run --rm -v ${PWD}/out/features:/app/features -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true db-tasks \
            cucumber --profile=${{ env.CUCUMBER_PROFILE }} --format junit --out /app/features --format pretty

      - name: Upload Feature Results
        uses: actions/upload-artifact@v2
        with:
          name: Feature_Results
          path: ${PWD}/out/features/*

  publish:
    name: Publish
    runs-on: ubuntu-18.4
    needs: build

    steps:
      - name: Build Only
        uses: docker/build-push-action@v2
        if: false && github.ref != 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}
          repository: ${{ env.APP_REPOSITORY }}
          always_pull: true
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
          push: false
          build_args: APP_SHA=${{ steps.sha.outputs.short }}
