name: Pull Requests
on:
  repository_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  DOCKER_IMAGE: dfedigital/school-experience
  CONTAINER: school-experience
  CUCUMBER_PROFILE: continuous_integration

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
             dockerfile: "Dockerfile"

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.6'

      - name: Install Bundler
        run: |-
          gem install bundler --version=2.1.4

      - name: Bundle install
        run: |
          bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
          bundle config set without development
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Brakeman security scan
        run: |-
          bundle exec \
            brakeman --no-pager

      - name: Run GovUK Lint check
        run: |-
          bundle exec \
            rubocop app config lib features spec spec_external --format clang

      - name: Build Docker Compose container
        run: |-
          docker-compose -f docker-compose-local.yml build

      - name: Create Docker Compose stack
        run: |-
          docker-compose -f docker-compose-local.yml up -d
          WAIT_COUNT=0
          until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ $WAIT_COUNT -eq 12 ] ; do echo "WAIT COUNT $(( WAIT_COUNT++ ))" && sleep 5 ; done

      - name: Run Specs
        run: |-
          docker-compose -f docker-compose-local.yml run --rm db-tasks \
            rspec --format documentation --format RspecJunitFormatter --out /ci_build/rspec_results.xml

      - name: Upload Spec Results
        uses: actions/upload-artifact@v2
        with:
          name: Spec_Results
          path: rspec_results.xml

      - name: Run Cucumber features
        run: |-
          docker-compose -f docker-compose-local.yml run --rm -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true db-tasks \
            cucumber --profile=${{ env.CUCUMBER_PROFILE }} --format junit --out /ci_build/junit

      - name: Upload Feature Results
        uses: actions/upload-artifact@v2
        with:
          name: Feature_Results
          path: junit/*

  publish:
    name: Publish
    runs-on: ubuntu-18.04
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
          elif [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Prepare
        id: prep
        run: |
          echo org.opencontainers.image.title=${{ github.event.repository.name }}
          echo org.opencontainers.image.description=${{ github.event.repository.description }}
          echo org.opencontainers.image.url=${{ github.event.repository.html_url }}
          echo org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          echo org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          echo org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          echo org.opencontainers.image.revision=${{ github.sha }}
          echo org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: false && ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
