name: Link Trello card

on:
  pull_request:
    types: [ opened , edited]

permissions:
  contents: write
  id-token: write

jobs:
  attach-to-trello:
    name: Link Trello card to this PR
    environment: review
    runs-on: ubuntu-latest
    if: "!contains( 'dependabot[bot] snyk-bot' , github.actor )"
    steps:
      - uses: Azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch synk token from key vault
        uses: azure/CLI@v2
        id: fetch-keyvault-secret
        with:
          inlineScript: |
            TRELLO_KEY=$(az keyvault secret show --name "TRELLO-KEY" --vault-name "${{ secrets.INF_KEY_VAULT}}" --query "value" -o tsv)
            echo "::add-mask::$TRELLO_KEY"
            echo "TRELLO-KEY=$TRELLO_KEY" >> $GITHUB_OUTPUT
            TRELLO_TOKEN=$(az keyvault secret show --name "TRELLO-TOKEN" --vault-name "${{ secrets.INF_KEY_VAULT}}" --query "value" -o tsv)
            echo "::add-mask::$TRELLO_TOKEN"
            echo "TRELLO-TOKEN=$TRELLO_TOKEN" >> $GITHUB_OUTPUT

      - name: Add Trello Comment
        uses: DFE-Digital/github-actions/AddTrelloComment@master
        with:
          MESSAGE:      ${{ github.event.pull_request.html_url }}
          CARD:         "${{ github.event.pull_request.body }}"
          TRELLO-KEY:   ${{ steps.fetch-keyvault-secret.outputs.TRELLO-KEY }}
          TRELLO-TOKEN: ${{ steps.fetch-keyvault-secret.outputs.TRELLO-TOKEN }}
